-- Flight Management System
-- Neon PostgreSQL schema
-- Based strictly on the supplied Hackathon Feature List.
-- PostgreSQL/Neon is used instead of the PDF's Supabase Postgres reference.
-- This script is non-destructive: it creates the required schema only if objects do not exist.
-- It does NOT drop tables, delete data, or reset an existing database.

BEGIN;

-- =========================
-- ENUM TYPES
-- =========================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'flight_status') THEN
        CREATE TYPE flight_status AS ENUM ('scheduled', 'cancelled');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'seat_class') THEN
        CREATE TYPE seat_class AS ENUM ('first', 'business', 'economy');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fare_type') THEN
        CREATE TYPE fare_type AS ENUM ('basic_economy', 'flexible');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_status') THEN
        CREATE TYPE booking_status AS ENUM (
            'held',
            'confirmed',
            'cancelled',
            'refunded',
            'rebooked',
            'credit_issued'
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'hold_status') THEN
        CREATE TYPE hold_status AS ENUM ('active', 'expired', 'converted', 'cancelled');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'refund_status') THEN
        CREATE TYPE refund_status AS ENUM ('pending', 'processing', 'completed', 'failed');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'refund_method') THEN
        CREATE TYPE refund_method AS ENUM ('original_payment', 'travel_credit');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'waitlist_status') THEN
        CREATE TYPE waitlist_status AS ENUM ('waiting', 'promoted', 'expired', 'cancelled');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'admin_role') THEN
        CREATE TYPE admin_role AS ENUM ('super_admin', 'ops_agent');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'overbooking_policy') THEN
        CREATE TYPE overbooking_policy AS ENUM ('hard_never_oversell', 'buffer_allowed');
    END IF;
END $$;


-- =========================
-- PASSENGERS
-- =========================

CREATE TABLE IF NOT EXISTS passengers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_passengers_email ON passengers(email);


-- =========================
-- ADMIN USERS
-- Required by PDF for role tiers.
-- Authentication itself is outside this schema/step.
-- =========================

CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role admin_role NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================
-- FLIGHTS
-- =========================

CREATE TABLE IF NOT EXISTS flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR(50) NOT NULL,
    origin VARCHAR(100) NOT NULL,
    destination VARCHAR(100) NOT NULL,
    departure_datetime TIMESTAMPTZ NOT NULL,
    arrival_datetime TIMESTAMPTZ NOT NULL,

    total_seats INTEGER NOT NULL,
    first_seats INTEGER NOT NULL,
    business_seats INTEGER NOT NULL,
    economy_seats INTEGER NOT NULL,

    available_first INTEGER NOT NULL,
    available_business INTEGER NOT NULL,
    available_economy INTEGER NOT NULL,

    overbooking_policy overbooking_policy NOT NULL DEFAULT 'hard_never_oversell',
    overbooking_buffer INTEGER NOT NULL DEFAULT 0,

    status flight_status NOT NULL DEFAULT 'scheduled',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_flight_route
        CHECK (origin <> destination),

    CONSTRAINT chk_flight_datetime
        CHECK (arrival_datetime > departure_datetime),

    CONSTRAINT chk_total_seats_positive
        CHECK (total_seats > 0),

    CONSTRAINT chk_first_seats_positive
        CHECK (first_seats > 0),

    CONSTRAINT chk_business_seats_positive
        CHECK (business_seats > 0),

    CONSTRAINT chk_economy_seats_positive
        CHECK (economy_seats > 0),

    CONSTRAINT chk_seat_class_sum
        CHECK (first_seats + business_seats + economy_seats = total_seats),

    CONSTRAINT chk_available_first
        CHECK (available_first >= 0 AND available_first <= first_seats),

    CONSTRAINT chk_available_business
        CHECK (available_business >= 0 AND available_business <= business_seats),

    CONSTRAINT chk_available_economy
        CHECK (available_economy >= 0 AND available_economy <= economy_seats),

    CONSTRAINT chk_overbooking_buffer
        CHECK (overbooking_buffer >= 0)
);

-- Duplicate flight number detection for same day/route.
CREATE UNIQUE INDEX IF NOT EXISTS uq_flight_number_route_day
ON flights (
    flight_number,
    origin,
    destination,
    ((departure_datetime AT TIME ZONE 'UTC')::date)
);

CREATE INDEX IF NOT EXISTS idx_flights_route_departure
ON flights(origin, destination, departure_datetime);

CREATE INDEX IF NOT EXISTS idx_flights_departure_date
ON flights(departure_datetime);


-- =========================
-- SEAT MAP / PHYSICAL SEATS
-- =========================

CREATE TABLE IF NOT EXISTS flight_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id BIGINT NOT NULL REFERENCES flights(id) ON DELETE RESTRICT,
    seat_number VARCHAR(20) NOT NULL,
    seat_class seat_class NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_flight_seat UNIQUE (flight_id, seat_number)
);

CREATE INDEX IF NOT EXISTS idx_flight_seats_flight_class
ON flight_seats(flight_id, seat_class);


-- =========================
-- FARE RULES
-- =========================

CREATE TABLE IF NOT EXISTS fare_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fare_type fare_type NOT NULL UNIQUE,

    changes_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    seat_selection_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    refundable BOOLEAN NOT NULL DEFAULT FALSE,
    credit_only BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_fare_rule_refund_mode
        CHECK (NOT (refundable = TRUE AND credit_only = TRUE))
);


-- =========================
-- FLIGHT FARES / PRICING
-- =========================

CREATE TABLE IF NOT EXISTS flight_fares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id BIGINT NOT NULL REFERENCES flights(id) ON DELETE RESTRICT,
    fare_rule_id BIGINT NOT NULL REFERENCES fare_rules(id) ON DELETE RESTRICT,
    seat_class seat_class NOT NULL,
    currency VARCHAR(3) NOT NULL,
    price NUMERIC(12,2) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_fare_price_nonnegative
        CHECK (price >= 0),

    CONSTRAINT chk_currency
        CHECK (char_length(currency) = 3),

    CONSTRAINT uq_flight_fare
        UNIQUE (flight_id, fare_rule_id, seat_class, currency)
);

CREATE INDEX IF NOT EXISTS idx_flight_fares_flight
ON flight_fares(flight_id);


-- =========================
-- PRICE / SEAT HOLDS
-- =========================

CREATE TABLE IF NOT EXISTS seat_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id BIGINT NOT NULL REFERENCES flights(id) ON DELETE RESTRICT,
    passenger_id BIGINT NOT NULL REFERENCES passengers(id) ON DELETE RESTRICT,

    seat_class seat_class NOT NULL,
    quantity INTEGER NOT NULL,

    fare_rule_id BIGINT REFERENCES fare_rules(id) ON DELETE RESTRICT,
    price NUMERIC(12,2),
    currency VARCHAR(3),

    status hold_status NOT NULL DEFAULT 'active',
    idempotency_key VARCHAR(255),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    converted_at TIMESTAMPTZ,

    CONSTRAINT chk_hold_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_hold_price
        CHECK (price IS NULL OR price >= 0),

    CONSTRAINT chk_hold_expiry
        CHECK (expires_at > created_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_seat_hold_idempotency
ON seat_holds(idempotency_key)
WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_seat_holds_expiry
ON seat_holds(status, expires_at);

CREATE INDEX IF NOT EXISTS idx_seat_holds_flight
ON seat_holds(flight_id);


-- =========================
-- BOOKINGS
-- =========================

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_reference VARCHAR(30) NOT NULL UNIQUE,

    passenger_id BIGINT NOT NULL REFERENCES passengers(id) ON DELETE RESTRICT,
    flight_id BIGINT NOT NULL REFERENCES flights(id) ON DELETE RESTRICT,

    seat_class seat_class NOT NULL,
    fare_type fare_type NOT NULL,

    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    total_price NUMERIC(12,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,

    status booking_status NOT NULL DEFAULT 'confirmed',

    hold_id BIGINT REFERENCES seat_holds(id) ON DELETE RESTRICT,

    idempotency_key VARCHAR(255),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_booking_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_booking_unit_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_booking_total_price
        CHECK (total_price >= 0),

    CONSTRAINT chk_booking_total_calculation
        CHECK (total_price = unit_price * quantity),

    CONSTRAINT chk_booking_currency
        CHECK (char_length(currency) = 3)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_idempotency
ON bookings(idempotency_key)
WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bookings_flight
ON bookings(flight_id);

CREATE INDEX IF NOT EXISTS idx_bookings_passenger
ON bookings(passenger_id);


-- =========================
-- BOOKING PASSENGERS
-- Supports multi-passenger / partial cancellation requirements.
-- =========================

CREATE TABLE IF NOT EXISTS booking_passengers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT,
    passenger_id BIGINT NOT NULL REFERENCES passengers(id) ON DELETE RESTRICT,
    seat_number VARCHAR(20),
    individual_price NUMERIC(12,2) NOT NULL,

    CONSTRAINT chk_booking_passenger_price
        CHECK (individual_price >= 0),

    CONSTRAINT uq_booking_passenger
        UNIQUE (booking_id, passenger_id)
);


-- =========================
-- REFUNDS / TRAVEL CREDITS
-- =========================

CREATE TABLE IF NOT EXISTS refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT,

    amount NUMERIC(12,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    method refund_method NOT NULL,
    status refund_status NOT NULL DEFAULT 'pending',

    reason VARCHAR(255),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ,

    CONSTRAINT chk_refund_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_refund_currency
        CHECK (char_length(currency) = 3)
);

CREATE INDEX IF NOT EXISTS idx_refunds_status
ON refunds(status);


CREATE TABLE IF NOT EXISTS travel_credits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE RESTRICT,
    passenger_id BIGINT NOT NULL REFERENCES passengers(id) ON DELETE RESTRICT,

    amount NUMERIC(12,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,

    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,

    CONSTRAINT chk_credit_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_credit_currency
        CHECK (char_length(currency) = 3),

    CONSTRAINT chk_credit_expiry
        CHECK (expires_at > issued_at)
);

CREATE INDEX IF NOT EXISTS idx_travel_credits_expiry
ON travel_credits(expires_at);


-- =========================
-- WAITLIST
-- =========================

CREATE TABLE IF NOT EXISTS waitlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    flight_id BIGINT NOT NULL REFERENCES flights(id) ON DELETE RESTRICT,
    passenger_id BIGINT NOT NULL REFERENCES passengers(id) ON DELETE RESTRICT,

    seat_class seat_class NOT NULL,
    fare_type fare_type,

    priority_score INTEGER NOT NULL DEFAULT 0,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    status waitlist_status NOT NULL DEFAULT 'waiting',

    promoted_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,

    CONSTRAINT chk_waitlist_priority
        CHECK (priority_score >= 0)
);

CREATE INDEX IF NOT EXISTS idx_waitlist_promotion
ON waitlist(flight_id, seat_class, status, priority_score DESC, joined_at);

CREATE INDEX IF NOT EXISTS idx_waitlist_passenger
ON waitlist(passenger_id);


-- =========================
-- AUDIT LOG
-- =========================

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    admin_user_id BIGINT REFERENCES admin_users(id) ON DELETE RESTRICT,

    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,

    action VARCHAR(100) NOT NULL,

    old_values JSONB,
    new_values JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity
ON audit_logs(entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at
ON audit_logs(created_at);


-- =========================
-- FRAUD SCORE
-- =========================

CREATE TABLE IF NOT EXISTS fraud_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT,

    score NUMERIC(6,3),
    reason JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_fraud_score
        CHECK (score IS NULL OR (score >= 0 AND score <= 100))
);

CREATE INDEX IF NOT EXISTS idx_fraud_scores_booking
ON fraud_scores(booking_id);


-- =========================
-- SCHEDULE CHANGE / REBOOKING
-- =========================

CREATE TABLE IF NOT EXISTS flight_schedule_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    flight_id BIGINT NOT NULL REFERENCES flights(id) ON DELETE RESTRICT,

    old_origin VARCHAR(100),
    old_destination VARCHAR(100),
    old_departure_datetime TIMESTAMPTZ,
    old_arrival_datetime TIMESTAMPTZ,

    new_origin VARCHAR(100),
    new_destination VARCHAR(100),
    new_departure_datetime TIMESTAMPTZ,
    new_arrival_datetime TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_schedule_changes_flight
ON flight_schedule_changes(flight_id);


CREATE TABLE IF NOT EXISTS booking_rebookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT,
    old_flight_id BIGINT NOT NULL REFERENCES flights(id) ON DELETE RESTRICT,
    new_flight_id BIGINT REFERENCES flights(id) ON DELETE RESTRICT,

    reason VARCHAR(255),
    fare_policy_overridden BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================
-- HELPFUL INTEGRITY INDEXES
-- =========================

CREATE INDEX IF NOT EXISTS idx_bookings_status
ON bookings(status);

CREATE INDEX IF NOT EXISTS idx_flights_status
ON flights(status);

COMMIT;
